FROM tumgis/3dcitydb-web-map:alpine-v2.0.0

WORKDIR /var/www/google-tiles-flight

COPY --chown=node:node src/ /var/www/google-tiles-flight/src/
COPY --chown=node:node index.html /var/www/google-tiles-flight/
COPY --chown=node:node asset/ /var/www/google-tiles-flight/asset/
COPY --chown=node:node scripts/server.js /var/www/google-tiles-flight/scripts/server.js

RUN mkdir -p /var/www/google-tiles-flight/asset/gate-paths \
    && chown -R node:node /var/www/google-tiles-flight/asset/gate-paths

EXPOSE 8000

CMD ["node", "/var/www/google-tiles-flight/scripts/server.js"]
